# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# =====================================================================================================================
# installation (https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/):
#   gem install bundler
#   cd directory
#   bundle config local.jekyll-last-modified-at C:/Users/phoenix/workspace/jekyll-last-modified-at
#     # bundle config --delete local.jekyll-last-modified-at
#   bundle install
#     bundle update
# running:
#   bundle exec jekyll serve -t --incremental

safe: false
plugins:
  - jekyll-pandoc
  # - jekyll-last-modified-at
# source: "source" # source change is forbidden by github

# =====================================================================================================================
# Site settings
# =====================================================================================================================

title: "Information Security"
email: "phonexicum@yandex.ru"
repository: phonexicum/phonexicum.github.io
description: > # this means to ignore newlines until "baseurl:"
  I created this site in a burst of information security studying to organize my mind and create some kind of cheatsheet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phonexicum.github.io" # the base hostname & protocol for your site
twitter_username: phonexicum
github_username:  phonexicum

future: true # This will show posts with future date

# =====================================================================================================================
# Build settings
# =====================================================================================================================
exclude:
    - vendor
    - "run.sh"
    - "run.sh.bat"
    - "Gemfile"
    - "Gemfile.lock"
    - "Markdown-csl"
    - "static.phonexicum.github.io"
    - "README.md"

# =====================================================================================================================
# Markdown build settings
# =====================================================================================================================

# https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers
highlighter: rouge

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
kramdown:
  auto_id_stripping: true
  auto_ids: true
  coderay_line_numbers: ":table"
  input: GFM
  hard_wrap: true
  parse_span_html: true
  remove_span_html_tags: false

  parse_block_html: false
  toc_levels: 1..3

  remove_block_html_tags: true

# # Build settings
# markdown: redcarpet
# markdown_ext:  markdown,mkdown,mkdn,mkd,md
# redcarpet:
#   extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# # Build settings
# markdown: Pandoc
# markdown_ext:  markdown,mkdown,mkdn,mkd,md
# pandoc:
#   # flags: '-f +auto_identifiers+implicit_header_references'
#   extensions:
#     - template: '_includes/toc.html'
#     - toc                                 # Good toc alternative: https://github.com/ghiculescu/jekyll-table-of-contents 
#     - toc-depth: 5

#     - normalize
#     - smart
#     - mathjax

#     - csl: Markdown-csl/apa.csl
# #    - bibliography: bibliography/references.bib

# Alternative csls:
#   https://github.com/citation-style-language/styles
